/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectmanagement;

import javax.swing.JOptionPane;

/**
 *
 * @author quynh
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
        empID.setText(String.valueOf(Emp.empID));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        empID = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        listProj = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        listProject = new javax.swing.JButton();
        listTask = new javax.swing.JButton();
        listUser = new javax.swing.JButton();
        listEmployee = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Logged In As:");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(20, 430, 120, 22);

        empID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        empID.setText("empID");
        jPanel2.add(empID);
        empID.setBounds(150, 430, 60, 22);

        jButton1.setBackground(new java.awt.Color(255, 51, 153));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProjectMangement/Image/logout.png"))); // NOI18N
        jButton1.setText("Logout");
        jButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(680, 10, 100, 40);

        listProj.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        listProj.setText("List Project: ");
        jPanel2.add(listProj);
        listProj.setBounds(30, 130, 134, 29);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("List Task: ");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(31, 290, 120, 29);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("List User: ");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(370, 130, 120, 29);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setText("List Employee: ");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(370, 290, 162, 29);

        listProject.setBackground(new java.awt.Color(153, 255, 153));
        listProject.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProjectMangement/Image/listProj.png"))); // NOI18N
        listProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listProjectActionPerformed(evt);
            }
        });
        jPanel2.add(listProject);
        listProject.setBounds(180, 120, 120, 60);

        listTask.setBackground(new java.awt.Color(153, 255, 153));
        listTask.setForeground(new java.awt.Color(255, 255, 255));
        listTask.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProjectMangement/Image/listTask.png"))); // NOI18N
        listTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listTaskActionPerformed(evt);
            }
        });
        jPanel2.add(listTask);
        listTask.setBounds(180, 290, 120, 60);

        listUser.setBackground(new java.awt.Color(153, 255, 153));
        listUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProjectMangement/Image/listUser.png"))); // NOI18N
        listUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listUserActionPerformed(evt);
            }
        });
        jPanel2.add(listUser);
        listUser.setBounds(570, 120, 120, 60);

        listEmployee.setBackground(new java.awt.Color(153, 255, 153));
        listEmployee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProjectMangement/Image/listEmp.png"))); // NOI18N
        jPanel2.add(listEmployee);
        listEmployee.setBounds(570, 290, 120, 60);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProjectMangement/Image/backgroundMenu.jpg"))); // NOI18N
        background.setText("jLabel1");
        jPanel2.add(background);
        background.setBounds(0, 0, 820, 475);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 820, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        login login1 = new login();
        login1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void listProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listProjectActionPerformed
        ListProject list = new ListProject();
        list.setVisible(true);
        list.setTitle("Project");
        this.dispose();
    }//GEN-LAST:event_listProjectActionPerformed

    private void listTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listTaskActionPerformed
        if(Emp.empDivision.equals("Employee")){
            ListTask list = new ListTask();
            list.setVisible(true);
            list.setTitle("Task");
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Only Employee can use!");
        }
        
    }//GEN-LAST:event_listTaskActionPerformed

    private void listUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listUserActionPerformed
        if(Emp.empDivision.equals("CEO")){
            
        } else {
            JOptionPane.showMessageDialog(null, "Only CEO can use!");
        }
    }//GEN-LAST:event_listUserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel empID;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton listEmployee;
    private javax.swing.JLabel listProj;
    private javax.swing.JButton listProject;
    private javax.swing.JButton listTask;
    private javax.swing.JButton listUser;
    // End of variables declaration//GEN-END:variables
}
